import { INTRO_MISSION } from "@/lib/content/seed";
import type { Mission } from "@/lib/domain/types";

const PRACTICAL_A1_SOURCE = {
  id: "00000000-0000-0000-0000-000000000101",
  title: "Source-backed beginner practical French reference set",
  reference: "Content-owner source record: A1 cafe, food, travel, and rescue phrases",
  trustLevel: "reference",
} as const;

export const CAFE_MISSION: Mission = {
  id: "mission-cafe-food-v1",
  slug: "cafe-food",
  title: "Order cafe food politely",
  description: "Order one item, ask the price, and use safer everyday cafe French.",
  outcome: "Order a coffee or croissant politely and avoid sounding too blunt.",
  estimatedMinutes: 8,
  cefrLevel: "A1",
  sources: [PRACTICAL_A1_SOURCE],
  contentItems: [
    {
      id: "phrase-cafe-je-voudrais-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je voudrais un café, s'il vous plaît.",
      englishMeaning: "I would like a coffee, please.",
      literalMeaning: "I would want a coffee, if it pleases you.",
      register: "neutral",
      usageContext: "Safe polite default for ordering in cafes, restaurants, and shops.",
      cefrLevel: "A1",
      grammarTags: ["polite-request", "cafe", "vouloir"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
      reviewerNotes: "Starter phrase. Needs qualified review before strong public accuracy claims.",
    },
    {
      id: "phrase-cafe-je-prends-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je prends un croissant.",
      englishMeaning: "I will have a croissant.",
      register: "neutral",
      usageContext: "Natural everyday phrase for choosing or ordering something.",
      cefrLevel: "A1",
      grammarTags: ["ordering", "cafe"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-cafe-combien-v1",
      version: 1,
      type: "phrase",
      frenchText: "C'est combien ?",
      englishMeaning: "How much is it?",
      literalMeaning: "It is how much?",
      register: "neutral",
      usageContext: "Short everyday question for paying or checking a price.",
      cefrLevel: "A1",
      grammarTags: ["price", "question"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-cafe-addition-v1",
      version: 1,
      type: "phrase",
      frenchText: "L'addition, s'il vous plaît.",
      englishMeaning: "The bill, please.",
      register: "neutral",
      usageContext: "Useful in restaurants; cafes may also use counter payment.",
      cefrLevel: "A1",
      grammarTags: ["restaurant", "politeness"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "rule-cafe-politeness-v1",
      version: 1,
      type: "grammar",
      frenchText: "Je voudrais...",
      englishMeaning: "I would like...",
      literalMeaning: "I would want...",
      register: "neutral",
      usageContext: "Use je voudrais as a safer polite request instead of defaulting to je veux.",
      cefrLevel: "A1",
      grammarTags: ["politeness", "conditional-chunk"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
  ],
  activities: [
    {
      id: "act-cafe-meaning-v1",
      type: "multiple_choice",
      prompt: "What does “Je voudrais un café, s'il vous plaît” mean?",
      promptFrenchSegments: ["Je voudrais un café, s'il vous plaît"],
      helperText: "Start with meaning before production.",
      contentItemIds: ["phrase-cafe-je-voudrais-v1"],
      grammarRuleIds: ["rule-cafe-politeness-v1"],
      estimatedSeconds: 20,
      choices: [
        { id: "a", label: "I have a coffee, please.", language: "en" },
        { id: "b", label: "I would like a coffee, please.", language: "en" },
        { id: "c", label: "I am a coffee, please.", language: "en" },
      ],
      acceptedAnswers: [{ value: "b" }],
      feedbackCorrect: "Right. Je voudrais is the safer polite way to say I would like.",
      feedbackIncorrect: "Je voudrais un café, s'il vous plaît means I would like a coffee, please.",
    },
    {
      id: "act-cafe-politeness-v1",
      type: "multiple_choice",
      prompt: "Which cafe order is the safer polite default?",
      promptFrenchSegments: [],
      helperText: "Both may be understood, but one is better as a beginner default.",
      contentItemIds: ["phrase-cafe-je-voudrais-v1", "rule-cafe-politeness-v1"],
      grammarRuleIds: ["rule-cafe-politeness-v1"],
      estimatedSeconds: 25,
      choices: [
        { id: "a", label: "Je veux un café.", language: "fr" },
        { id: "b", label: "Je voudrais un café, s'il vous plaît.", language: "fr" },
      ],
      acceptedAnswers: [{ value: "b" }],
      feedbackCorrect: "Correct. Je voudrais is safer and more polite than je veux as your default.",
      feedbackIncorrect: "Use Je voudrais un café, s'il vous plaît as the safer polite default.",
    },
    {
      id: "act-cafe-fill-order-v1",
      type: "fill_blank",
      prompt: "Complete the order: Bonjour, je voudrais un ___, s'il vous plaît.",
      promptFrenchSegments: ["Bonjour, je voudrais un ___, s'il vous plaît."],
      helperText: "Type the missing item.",
      placeholder: "Type the missing word",
      targetText: "Bonjour, je voudrais un café, s'il vous plaît.",
      contentItemIds: ["phrase-cafe-je-voudrais-v1"],
      grammarRuleIds: ["rule-cafe-politeness-v1"],
      estimatedSeconds: 30,
      acceptedAnswers: [{ value: "café", allowAccentless: true }],
      feedbackCorrect: "Nice. You completed a polite cafe order.",
      feedbackIncorrect: "The missing word is café.",
    },
    {
      id: "act-cafe-type-order-v1",
      type: "typing",
      prompt: "Type: I would like a coffee, please.",
      promptFrenchSegments: [],
      helperText: "Use the safe polite version.",
      placeholder: "Je voudrais...",
      targetText: "Je voudrais un café, s'il vous plaît.",
      contentItemIds: ["phrase-cafe-je-voudrais-v1"],
      grammarRuleIds: ["rule-cafe-politeness-v1"],
      estimatedSeconds: 45,
      acceptedAnswers: [
        { value: "Je voudrais un café, s'il vous plaît.", allowAccentless: true },
        { value: "Je voudrais un café s'il vous plaît.", allowAccentless: true },
      ],
      nearMisses: [
        {
          value: "Je veux un café",
          mistakeType: "register",
          ruleId: "rule-cafe-politeness-v1",
          explanation: "Je veux can sound blunt as a default cafe order. Je voudrais is safer and more polite.",
          correctedAnswer: "Je voudrais un café, s'il vous plaît.",
        },
      ],
      feedbackCorrect: "Good. That is a safe everyday cafe order.",
      feedbackIncorrect: "Use: Je voudrais un café, s'il vous plaît.",
    },
    {
      id: "act-cafe-sentence-builder-v1",
      type: "sentence_builder",
      prompt: "Build the sentence: I will have a croissant.",
      promptFrenchSegments: [],
      helperText: "Put the French chunks in order.",
      tokens: ["un", "croissant", "Je", "prends"],
      contentItemIds: ["phrase-cafe-je-prends-v1"],
      grammarRuleIds: ["phrase-cafe-je-prends-v1"],
      estimatedSeconds: 35,
      acceptedAnswers: [{ value: "Je prends un croissant." }],
      feedbackCorrect: "Correct. Je prends is natural for ordering or choosing something.",
      feedbackIncorrect: "The correct sentence is: Je prends un croissant.",
    },
    {
      id: "act-cafe-dictation-price-v1",
      type: "dictation",
      prompt: "Dictation self-check: type the price question.",
      promptFrenchSegments: [],
      helperText: "Play the audio, then type what you hear.",
      targetText: "C'est combien ?",
      placeholder: "Type the phrase",
      contentItemIds: ["phrase-cafe-combien-v1"],
      grammarRuleIds: ["phrase-cafe-combien-v1"],
      estimatedSeconds: 35,
      acceptedAnswers: [{ value: "C'est combien ?", allowAccentless: true }],
      feedbackCorrect: "Good. C'est combien ? is short and useful when paying.",
      feedbackIncorrect: "The target phrase is: C'est combien ?",
    },
    {
      id: "act-cafe-speak-bill-v1",
      type: "speak_repeat",
      prompt: "Speaking self-check: L'addition, s'il vous plaît.",
      promptFrenchSegments: ["L'addition, s'il vous plaît."],
      helperText: "Listen to the phrase where audio is supported, then say it out loud once. There is no recording or pronunciation score.",
      targetText: "L'addition, s'il vous plaît.",
      contentItemIds: ["phrase-cafe-addition-v1"],
      grammarRuleIds: ["phrase-cafe-addition-v1"],
      estimatedSeconds: 25,
      acceptedAnswers: [{ value: "completed" }],
      feedbackCorrect: "Good. That is a useful restaurant phrase.",
      feedbackIncorrect: "Try saying it once more: L'addition, s'il vous plaît.",
    },
  ],
};

export const TRAVEL_MISSION: Mission = {
  id: "mission-travel-basics-v1",
  slug: "travel-basics",
  title: "Handle basic travel questions",
  description: "Ask where something is, buy a ticket, ask for repeat help, and say you are lost.",
  outcome: "Ask for a station, buy a ticket, and recover when you do not understand.",
  estimatedMinutes: 9,
  cefrLevel: "A1",
  sources: [PRACTICAL_A1_SOURCE],
  contentItems: [
    {
      id: "phrase-travel-gare-v1",
      version: 1,
      type: "phrase",
      frenchText: "Où est la gare ?",
      englishMeaning: "Where is the station?",
      register: "neutral",
      usageContext: "Basic location question for travel.",
      cefrLevel: "A1",
      grammarTags: ["where-is", "travel"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-travel-billet-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je voudrais un billet pour Paris.",
      englishMeaning: "I would like a ticket to Paris.",
      register: "neutral",
      usageContext: "Buying a ticket. Swap Paris for the place needed.",
      cefrLevel: "A1",
      grammarTags: ["ticket", "travel", "polite-request"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-travel-train-time-v1",
      version: 1,
      type: "phrase",
      frenchText: "À quelle heure part le train ?",
      englishMeaning: "What time does the train leave?",
      register: "neutral",
      usageContext: "Useful at stations and when checking simple schedules.",
      cefrLevel: "A1",
      grammarTags: ["time", "train", "question"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-travel-repeat-v1",
      version: 1,
      type: "phrase",
      frenchText: "Pouvez-vous répéter, s'il vous plaît ?",
      englishMeaning: "Can you repeat, please?",
      register: "formal",
      usageContext: "Safe polite rescue phrase when someone speaks too fast.",
      cefrLevel: "A1",
      grammarTags: ["rescue-phrase", "politeness"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "phrase-travel-lost-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je suis perdu.",
      englishMeaning: "I am lost.",
      register: "neutral",
      usageContext: "Use perdue if the speaker is feminine.",
      cefrLevel: "A1",
      grammarTags: ["lost", "travel"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
    {
      id: "rule-travel-politeness-v1",
      version: 1,
      type: "grammar",
      frenchText: "Pouvez-vous... ?",
      englishMeaning: "Can you...?",
      register: "formal",
      usageContext: "A safe polite vous structure for asking strangers for help.",
      cefrLevel: "A1",
      grammarTags: ["politeness", "vous", "question"],
      sourceIds: [PRACTICAL_A1_SOURCE.id],
      verificationStatus: "needs_review",
      publicationStatus: "draft",
    },
  ],
  activities: [
    {
      id: "act-travel-meaning-gare-v1",
      type: "multiple_choice",
      prompt: "What does “Où est la gare ?” mean?",
      promptFrenchSegments: ["Où est la gare ?"],
      helperText: "Start with a basic travel question.",
      contentItemIds: ["phrase-travel-gare-v1"],
      grammarRuleIds: ["phrase-travel-gare-v1"],
      estimatedSeconds: 20,
      choices: [
        { id: "a", label: "Where is the station?", language: "en" },
        { id: "b", label: "When is the train?", language: "en" },
        { id: "c", label: "Where is the cafe?", language: "en" },
      ],
      acceptedAnswers: [{ value: "a" }],
      feedbackCorrect: "Correct. Où est la gare ? means Where is the station?",
      feedbackIncorrect: "Où est la gare ? means Where is the station?",
    },
    {
      id: "act-travel-fill-gare-v1",
      type: "fill_blank",
      prompt: "Complete: Où est la ___ ?",
      promptFrenchSegments: ["Où est la ___ ?"],
      helperText: "Type the word for station.",
      placeholder: "Type the missing word",
      targetText: "Où est la gare ?",
      contentItemIds: ["phrase-travel-gare-v1"],
      grammarRuleIds: ["phrase-travel-gare-v1"],
      estimatedSeconds: 25,
      acceptedAnswers: [{ value: "gare" }],
      feedbackCorrect: "Good. La gare means the station.",
      feedbackIncorrect: "The missing word is gare.",
    },
    {
      id: "act-travel-type-ticket-v1",
      type: "typing",
      prompt: "Type: I would like a ticket to Paris.",
      promptFrenchSegments: [],
      helperText: "Use the polite request chunk from the cafe topic too.",
      placeholder: "Je voudrais...",
      targetText: "Je voudrais un billet pour Paris.",
      contentItemIds: ["phrase-travel-billet-v1"],
      grammarRuleIds: ["rule-cafe-politeness-v1"],
      estimatedSeconds: 45,
      acceptedAnswers: [{ value: "Je voudrais un billet pour Paris." }],
      feedbackCorrect: "Correct. You can swap Paris for the destination you need.",
      feedbackIncorrect: "Use: Je voudrais un billet pour Paris.",
    },
    {
      id: "act-travel-sentence-builder-time-v1",
      type: "sentence_builder",
      prompt: "Build the sentence: What time does the train leave?",
      promptFrenchSegments: [],
      helperText: "Put the chunks in order.",
      tokens: ["part", "À", "quelle", "heure", "le", "train"],
      contentItemIds: ["phrase-travel-train-time-v1"],
      grammarRuleIds: ["phrase-travel-train-time-v1"],
      estimatedSeconds: 40,
      acceptedAnswers: [{ value: "À quelle heure part le train ?", allowAccentless: true }],
      feedbackCorrect: "Good. That question is useful at stations.",
      feedbackIncorrect: "The sentence is: À quelle heure part le train ?",
    },
    {
      id: "act-travel-dictation-repeat-v1",
      type: "dictation",
      prompt: "Dictation self-check: type the repeat-help phrase.",
      promptFrenchSegments: [],
      helperText: "Play the audio, then type what you hear.",
      targetText: "Pouvez-vous répéter, s'il vous plaît ?",
      placeholder: "Type the phrase",
      contentItemIds: ["phrase-travel-repeat-v1"],
      grammarRuleIds: ["rule-travel-politeness-v1"],
      estimatedSeconds: 45,
      acceptedAnswers: [
        { value: "Pouvez-vous répéter, s'il vous plaît ?", allowAccentless: true },
        { value: "Pouvez vous répéter s'il vous plaît ?", allowAccentless: true },
        { value: "Pouvez vous repeter s'il vous plait", allowAccentless: true },
      ],
      feedbackCorrect: "Good. This is a safe polite rescue phrase.",
      feedbackIncorrect: "The target phrase is: Pouvez-vous répéter, s'il vous plaît ?",
    },
    {
      id: "act-travel-fill-lost-v1",
      type: "fill_blank",
      prompt: "Complete: Je suis ___.",
      promptFrenchSegments: ["Je suis ___."],
      helperText: "Type the phrase for lost.",
      placeholder: "Type the missing word",
      targetText: "Je suis perdu.",
      contentItemIds: ["phrase-travel-lost-v1"],
      grammarRuleIds: ["phrase-travel-lost-v1"],
      estimatedSeconds: 25,
      acceptedAnswers: [{ value: "perdu" }, { value: "perdue" }],
      feedbackCorrect: "Correct. Use perdue if the speaker is feminine.",
      feedbackIncorrect: "Use perdu or perdue depending on the speaker.",
    },
    {
      id: "act-travel-speak-lost-v1",
      type: "speak_repeat",
      prompt: "Speaking self-check: Je suis perdu.",
      promptFrenchSegments: ["Je suis perdu."],
      helperText: "Listen to the phrase where audio is supported, then say it out loud once. There is no recording or pronunciation score.",
      targetText: "Je suis perdu.",
      contentItemIds: ["phrase-travel-lost-v1"],
      grammarRuleIds: ["phrase-travel-lost-v1"],
      estimatedSeconds: 25,
      acceptedAnswers: [{ value: "completed" }],
      feedbackCorrect: "Good. That is a useful emergency-style travel phrase.",
      feedbackIncorrect: "Try saying it once more: Je suis perdu.",
    },
  ],
};

export const SCORED_MISSIONS: Mission[] = [INTRO_MISSION, CAFE_MISSION, TRAVEL_MISSION];

export function getMissionBySlug(slug: string): Mission | undefined {
  return SCORED_MISSIONS.find((mission) => mission.slug === slug);
}

export function getMissionById(id: string): Mission | undefined {
  return SCORED_MISSIONS.find((mission) => mission.id === id);
}

export function getScoredActivityById(activityId: string) {
  return SCORED_MISSIONS
    .flatMap((mission) => mission.activities)
    .find((activity) => activity.id === activityId);
}

export function getScoredMissionSlugs() {
  return SCORED_MISSIONS.map((mission) => mission.slug);
}

export function getPublicScoredMissionSlugs() {
  return ["introduce-yourself"];
}

export function isPublicScoredMissionSlug(slug: string) {
  return getPublicScoredMissionSlugs().includes(slug);
}

