import type { Mission } from "@/lib/domain/types";

export const INTRO_MISSION: Mission = {
  id: "mission-introduce-yourself-v1",
  slug: "introduce-yourself",
  title: "Introduce yourself and talk about your day",
  description: "Build a short, natural introduction you can use with someone new.",
  outcome: "Say your name, age, origin, and one thing you do in everyday French.",
  estimatedMinutes: 10,
  cefrLevel: "A1",
  sources: [
    {
      id: "00000000-0000-0000-0000-000000000001",
      title: "Source-backed beginner French reference set",
      reference: "Content-owner source record: A1 introductions and avoir for age",
      trustLevel: "reference",
    },
  ],
  contentItems: [
    {
      id: "phrase-je-mappelle-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je m'appelle…",
      englishMeaning: "My name is…",
      literalMeaning: "I call myself…",
      register: "neutral",
      usageContext: "A safe everyday introduction.",
      cefrLevel: "A1",
      grammarTags: ["s'appeler", "introduction"],
      sourceIds: ["00000000-0000-0000-0000-000000000001"],
      verificationStatus: "source_validated",
      publicationStatus: "published",
    },
    {
      id: "phrase-moi-cest-v1",
      version: 1,
      type: "phrase",
      frenchText: "Moi, c'est…",
      englishMeaning: "I'm… / My name is…",
      register: "casual",
      usageContext: "Relaxed spoken introductions with friends or peers.",
      cefrLevel: "A1",
      grammarTags: ["introduction", "spoken-register"],
      sourceIds: ["00000000-0000-0000-0000-000000000001"],
      verificationStatus: "source_validated",
      publicationStatus: "published",
    },
    {
      id: "rule-age-avoir-v1",
      version: 1,
      type: "grammar",
      frenchText: "J'ai 20 ans.",
      englishMeaning: "I am 20 years old.",
      literalMeaning: "I have 20 years.",
      register: "neutral",
      usageContext: "Use avoir, not être, when stating age.",
      cefrLevel: "A1",
      grammarTags: ["avoir", "age"],
      sourceIds: ["00000000-0000-0000-0000-000000000001"],
      verificationStatus: "source_validated",
      publicationStatus: "published",
    },
    {
      id: "phrase-je-viens-de-v1",
      version: 1,
      type: "phrase",
      frenchText: "Je viens de Belfast.",
      englishMeaning: "I come from Belfast.",
      register: "neutral",
      usageContext: "Use this to say where you come from.",
      cefrLevel: "A1",
      grammarTags: ["venir de", "origin"],
      sourceIds: ["00000000-0000-0000-0000-000000000001"],
      verificationStatus: "source_validated",
      publicationStatus: "published",
    },
    {
      id: "phrase-aujourdhui-v1",
      version: 1,
      type: "phrase",
      frenchText: "Aujourd'hui, j'étudie le français.",
      englishMeaning: "Today, I am studying French.",
      register: "neutral",
      usageContext: "A short everyday sentence about what you are doing today.",
      cefrLevel: "A1",
      grammarTags: ["aujourd'hui", "étudier"],
      sourceIds: ["00000000-0000-0000-0000-000000000001"],
      verificationStatus: "source_validated",
      publicationStatus: "published",
    },
  ],
  activities: [
    {
      id: "act-name-meaning-v1",
      type: "multiple_choice",
      prompt: "What does “Je m'appelle Jamie” mean?",
      promptFrenchSegments: ["Je m'appelle Jamie"],
      helperText: "Choose the everyday meaning.",
      contentItemIds: ["phrase-je-mappelle-v1"],
      grammarRuleIds: [],
      estimatedSeconds: 25,
      choices: [
        { id: "a", label: "My name is Jamie.", language: "en" },
        { id: "b", label: "I am from Jamie.", language: "en" },
        { id: "c", label: "I like Jamie.", language: "en" },
      ],
      acceptedAnswers: [{ value: "a" }],
      feedbackCorrect: "Exactly. This is a neutral, safe everyday introduction.",
      feedbackIncorrect: "Use “Je m'appelle…” to say your name.",
    },
    {
      id: "act-age-fill-v1",
      type: "fill_blank",
      prompt: "Fill the gap: J'___ 20 ans.",
      promptFrenchSegments: ["J'___ 20 ans."],
      helperText: "French uses a verb meaning “to have” for age.",
      placeholder: "Type one word",
      contentItemIds: ["rule-age-avoir-v1"],
      grammarRuleIds: ["rule-age-avoir-v1"],
      estimatedSeconds: 25,
      acceptedAnswers: [{ value: "ai" }, { value: "ai", allowAccentless: true }],
      nearMisses: [
        {
          value: "suis",
          mistakeType: "grammar",
          ruleId: "rule-age-avoir-v1",
          explanation: "French uses avoir for age, not être.",
          correctedAnswer: "J'ai 20 ans.",
        },
      ],
      feedbackCorrect: "Yes—J'ai 20 ans is the standard pattern.",
      feedbackIncorrect: "For age, French uses avoir: J'ai 20 ans.",
    },
    {
      id: "act-age-typing-v1",
      type: "typing",
      prompt: "Write: I am 20 years old.",
      promptFrenchSegments: [],
      helperText: "Use the complete French sentence.",
      placeholder: "Write your answer in French",
      contentItemIds: ["rule-age-avoir-v1"],
      grammarRuleIds: ["rule-age-avoir-v1"],
      estimatedSeconds: 35,
      acceptedAnswers: [{ value: "J'ai 20 ans" }],
      nearMisses: [
        {
          value: "Je suis 20 ans",
          mistakeType: "grammar",
          ruleId: "rule-age-avoir-v1",
          explanation: "French uses avoir for age, not être.",
          correctedAnswer: "J'ai 20 ans.",
        },
      ],
      feedbackCorrect: "Great recall. French literally says “I have 20 years.”",
      feedbackIncorrect: "Use avoir for age: J'ai 20 ans.",
    },
    {
      id: "act-origin-builder-v1",
      type: "sentence_builder",
      prompt: "Put the words in order: I come from Belfast.",
      promptFrenchSegments: [],
      helperText: "Tap the words in their French order.",
      tokens: ["Je", "viens", "de", "Belfast"],
      contentItemIds: ["phrase-je-viens-de-v1"],
      grammarRuleIds: ["phrase-je-viens-de-v1"],
      estimatedSeconds: 35,
      acceptedAnswers: [{ value: "Je viens de Belfast" }],
      feedbackCorrect: "Well built. Use venir de for where you come from.",
      feedbackIncorrect: "The safe pattern is: Je viens de Belfast.",
    },
    {
      id: "act-dictation-v1",
      type: "dictation",
      prompt: "Dictation practice: type the phrase you hear.",
      promptFrenchSegments: [],
      helperText: "Play the audio, then type what you hear.",
      targetText: "Je m'appelle Jamie.",
      placeholder: "Type the phrase",
      contentItemIds: ["phrase-je-mappelle-v1"],
      grammarRuleIds: [],
      estimatedSeconds: 40,
      acceptedAnswers: [{ value: "Je m'appelle Jamie" }],
      feedbackCorrect: "Nice. You matched the sounds to the words.",
      feedbackIncorrect: "The target phrase is: Je m'appelle Jamie.",
    },
    {
      id: "act-speak-repeat-v1",
      type: "speak_repeat",
      prompt: "Say this out loud: Aujourd'hui, j'étudie le français.",
      promptFrenchSegments: ["Aujourd'hui, j'étudie le français."],
      helperText: "This is a speaking self-check. No recording, transcription, or pronunciation score is used.",
      targetText: "Aujourd'hui, j'étudie le français.",
      contentItemIds: ["phrase-aujourdhui-v1"],
      grammarRuleIds: [],
      estimatedSeconds: 30,
      acceptedAnswers: [{ value: "completed" }],
      feedbackCorrect: "Good work. Notice the rhythm: aujourd'hui | j'étudie | le français.",
      feedbackIncorrect: "Try the phrase once more at a comfortable pace.",
    },
    {
      id: "act-register-v1",
      type: "multiple_choice",
      prompt: "Which version is more casual in a relaxed spoken introduction?",
      promptFrenchSegments: [],
      helperText: "Both can be useful—choose the relaxed spoken option.",
      contentItemIds: ["phrase-je-mappelle-v1", "phrase-moi-cest-v1"],
      grammarRuleIds: [],
      estimatedSeconds: 25,
      choices: [
        { id: "a", label: "Je m'appelle Jamie.", language: "fr" },
        { id: "b", label: "Moi, c'est Jamie.", language: "fr" },
      ],
      acceptedAnswers: [{ value: "b", register: "casual" }],
      feedbackCorrect: "Right. “Moi, c'est…” is a relaxed spoken option; “Je m'appelle…” is the safer neutral default.",
      feedbackIncorrect: "“Je m'appelle…” is neutral. “Moi, c'est…” is more casual and spoken.",
    },
  ],
};

export const getSeedMission = () => INTRO_MISSION;

