// Prints a migration that puts the published introduction mission's activity
// payloads back in lockstep with the verified runtime curriculum. Run it
// whenever seed copy changes and save the output as a new migration:
//
//   npx tsx content-tools/generate-intro-sync.ts > supabase/migrations/<stamp>_sync_intro_activity_copy.sql

import { getSeedMission } from "../lib/content/seed";

const mission = getSeedMission();

const rows = mission.activities
  .map((activity) => `    ('${activity.id}', $json$\n      ${JSON.stringify(activity)}\n    $json$::jsonb)`)
  .join(",\n");

process.stdout.write(`-- Generated by content-tools/generate-intro-sync.ts from lib/content/seed.ts.
-- Keeps the published introduction mission's activity payloads in lockstep
-- with the verified runtime curriculum after copy changes.

with canonical_activities (id, payload) as (
  values
${rows}
)
update public.activities as activity
set payload = canonical.payload
from canonical_activities as canonical
where activity.id = canonical.id
  and activity.mission_id = '${mission.id}'
  and activity.payload is distinct from canonical.payload;
`);
