import { describe, expect, it } from "vitest";
import { resolveDevelopmentLearnerId } from "../lib/auth/development-user";

describe("development learner isolation", () => {
  it("accepts the narrow identifier generated by the Playwright fixture", () => {
    expect(resolveDevelopmentLearnerId("e2e-012345abcdef-0", "demo-learner"))
      .toBe("e2e-012345abcdef-0");
  });

  it.each([
    undefined,
    "demo-learner",
    "e2e-not-a-hash-0",
    "e2e-012345abcdef",
    "e2e-012345abcdef-0/../other",
  ])("falls back for an invalid isolated learner identifier: %s", (candidate) => {
    expect(resolveDevelopmentLearnerId(candidate, "demo-learner")).toBe("demo-learner");
  });
});
